---
abstract: 'Preforking AnyEvent HTTP server for PSGI'
author:
  - 'Masahiro Nagano <kazeburo {at} gmail.com>'
build_requires:
  Capture::Tiny: 0
  LWP::UserAgent: 0
  Plack::Test::Suite: 0
  Test::More: 0
  Test::Requires: 0
  Test::SharedFork: 0
  Test::TCP: 2.00
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.4, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Twiggy-Prefork
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Plack::Handler::Twiggy::Prefork:
    file: lib/Plack/Handler/Twiggy/Prefork.pm
  Twiggy::Prefork:
    file: lib/Twiggy/Prefork.pm
    version: 0.07
  Twiggy::Prefork::Server:
    file: lib/Twiggy/Prefork/Server.pm
  Twiggy::Prefork::Server::SS:
    file: lib/Twiggy/Prefork/Server/SS.pm
requires:
  AnyEvent: 0
  Parallel::Prefork: 0.13
  Server::Starter: 0
  Twiggy: 0.1020
resources:
  bugtracker: https://github.com/kazeburo/Twiggy-Prefork/issues
  homepage: https://github.com/kazeburo/Twiggy-Prefork
  repository: git://github.com/kazeburo/Twiggy-Prefork.git
version: 0.07
x_contributors:
  - 'nhayashi <hayashi.naritoshi@dena.jp>'
  - 'Masahiro Nagano <kazeburo@gmail.com>'
